"""FastAPI server for the customer support agent — Cloud Run entrypoint.

Uses Anthropic Claude models via Microsoft Foundry (Azure AI Foundry).
"""
import logging
import os
from pathlib import Path

# Load .env before any other imports so env vars are available at module level
from dotenv import load_dotenv
load_dotenv(Path(__file__).resolve().parent.parent / ".env")

import secrets
from opentelemetry import context as otel_context, trace
from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel
from starlette.middleware.base import BaseHTTPMiddleware
from .tracing import get_azure_tracer, setup_tracer_provider, extract_context_from_headers, flush_traces
from .graph import invoke_support

SUPPORT_API_KEY = os.environ.get("SUPPORT_API_KEY")


class ApiKeyMiddleware(BaseHTTPMiddleware):
    """Reject requests without a valid x-api-key header.

    Skipped when SUPPORT_API_KEY is not set (local dev) or for health checks.
    """
    EXEMPT_PATHS = {"/health", "/docs", "/openapi.json"}

    async def dispatch(self, request: Request, call_next):
        if not SUPPORT_API_KEY or request.url.path in self.EXEMPT_PATHS:
            return await call_next(request)

        key = request.headers.get("x-api-key", "")
        if not secrets.compare_digest(key, SUPPORT_API_KEY):
            return JSONResponse(status_code=403, content={"error": "Forbidden"})

        return await call_next(request)

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)

# Initialize tracing on startup
_tracing_initialized = False


def _init_tracing():
    global _tracing_initialized
    if not _tracing_initialized:
        os.environ.setdefault("AZURE_TRACING_GEN_AI_CONTENT_RECORDING_ENABLED", "true")
        get_azure_tracer()
        _tracing_initialized = True


app = FastAPI(title="LangGraph Customer Support Agent", version="1.0.0")

app.add_middleware(ApiKeyMiddleware)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


class SupportRequest(BaseModel):
    message: str
    customer_id: str | None = None


@app.on_event("startup")
async def startup():
    _init_tracing()


@app.get("/health")
async def health():
    return {"status": "healthy"}


@app.post("/support")
async def support(body: SupportRequest, request: Request):
    """Handle support requests with W3C Trace Context propagation.

    Extracts traceparent/tracestate/baggage from incoming HTTP headers so
    that all agent spans appear as children of the caller's span.
    """
    setup_tracer_provider()
    parent_ctx = extract_context_from_headers(request.headers)
    token = otel_context.attach(parent_ctx)

    tracer = trace.get_tracer(__name__)

    try:
        with tracer.start_as_current_span(
            "handle_request",
            kind=trace.SpanKind.SERVER,
            attributes={"http.method": "POST", "http.route": "/support"},
        ) as span:
            result = invoke_support(body.message, body.customer_id)

            logger.info(f"Response generated by: {result['handled_by']}")
            span.set_attribute("agent.handled_by", result["handled_by"])
            span.set_attribute("agent.query_type", result["query_type"])
            span.set_attribute("http.status_code", 200)
            flush_traces()

            return {
                "response": result["response"],
                "metadata": {
                    "handled_by": result["handled_by"],
                    "query_type": result["query_type"],
                    "needs_escalation": result["needs_escalation"],
                },
            }
    except Exception as e:
        logger.error(f"Error processing request: {str(e)}", exc_info=True)
        return JSONResponse(status_code=500, content={"error": "Internal server error"})
    finally:
        otel_context.detach(token)
        flush_traces()
