"""FastAPI server for the customer support agent — Cloud Run entrypoint.

Uses Anthropic Claude models via Microsoft Foundry (Azure AI Foundry).
"""
import logging
import os
from pathlib import Path

# Load .env before any other imports so env vars are available at module level
from dotenv import load_dotenv
load_dotenv(Path(__file__).resolve().parent.parent / ".env")

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel
from .tracing import get_azure_tracer, flush_traces
from .graph import invoke_support

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)

# Initialize tracing on startup
_tracing_initialized = False


def _init_tracing():
    global _tracing_initialized
    if not _tracing_initialized:
        os.environ.setdefault("AZURE_TRACING_GEN_AI_CONTENT_RECORDING_ENABLED", "true")
        get_azure_tracer()
        _tracing_initialized = True


app = FastAPI(title="LangGraph Customer Support Agent", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


class SupportRequest(BaseModel):
    message: str
    customer_id: str | None = None


@app.on_event("startup")
async def startup():
    _init_tracing()


@app.get("/health")
async def health():
    return {"status": "healthy"}


@app.post("/support")
async def support(request: SupportRequest):
    try:
        result = invoke_support(request.message, request.customer_id)
        logger.info(f"Response generated by: {result['handled_by']}")
        flush_traces()

        return {
            "response": result["response"],
            "metadata": {
                "handled_by": result["handled_by"],
                "query_type": result["query_type"],
                "needs_escalation": result["needs_escalation"],
            }
        }
    except Exception as e:
        logger.error(f"Error processing request: {str(e)}", exc_info=True)
        flush_traces()
        return JSONResponse(status_code=500, content={"error": "Internal server error"})
