"""AWS Lambda handler for the customer support agent with Azure AI tracing."""
import json
import logging
import os
from .tracing import flush_traces
from .graph_aws import invoke_support

logger = logging.getLogger()
logger.setLevel(logging.INFO)

# Initialize tracing on cold start
_tracing_initialized = False


def _init_tracing():
    """Initialize OpenTelemetry tracing."""
    global _tracing_initialized
    if not _tracing_initialized:
        from .tracing import get_otel_tracer
        # Just getting the tracer will initialize it
        get_otel_tracer()
        logger.info("OpenTelemetry tracing initialized")
        _tracing_initialized = True


def handler(event, context):
    """
    Lambda handler for API Gateway integration.
    
    Expected request body:
    {
        "message": "Customer's message here",
        "customer_id": "optional-customer-id"
    }
    """
    # Initialize tracing
    _init_tracing()
    
    logger.info(f"Received event: {json.dumps(event)}")
    
    try:
        # Parse request body
        if isinstance(event.get("body"), str):
            body = json.loads(event["body"])
        else:
            body = event.get("body", event)
        
        message = body.get("message")
        if not message:
            return {
                "statusCode": 400,
                "headers": {
                    "Content-Type": "application/json",
                    "Access-Control-Allow-Origin": "*",
                },
                "body": json.dumps({"error": "Message is required"})
            }
        
        customer_id = body.get("customer_id")
        
        # Invoke the support graph with tracing
        result = invoke_support(message, customer_id)
        
        logger.info(f"Response generated by: {result['handled_by']}")
        
        # Flush traces before returning
        flush_traces()
        
        return {
            "statusCode": 200,
            "headers": {
                "Content-Type": "application/json",
                "Access-Control-Allow-Origin": "*",
            },
            "body": json.dumps({
                "response": result["response"],
                "metadata": {
                    "handled_by": result["handled_by"],
                    "query_type": result["query_type"],
                    "needs_escalation": result["needs_escalation"],
                }
            })
        }
        
    except Exception as e:
        logger.error(f"Error processing request: {str(e)}", exc_info=True)
        flush_traces()
        return {
            "statusCode": 500,
            "headers": {
                "Content-Type": "application/json",
                "Access-Control-Allow-Origin": "*",
            },
            "body": json.dumps({"error": "Internal server error"})
        }
