"""AWS Lambda handler for the customer support agent with Azure AI tracing."""
import json
import logging
from opentelemetry import context as otel_context, trace
from .graph import invoke_support
from .tracing import setup_tracer_provider, extract_context_from_headers, flush_traces

logger = logging.getLogger()
logger.setLevel(logging.INFO)

CORS_HEADERS = {
    "Content-Type": "application/json",
    "Access-Control-Allow-Origin": "*",
}


def handler(event, context):
    """Lambda handler for API Gateway integration.

    Extracts W3C Trace Context (traceparent/tracestate) and Baggage from
    incoming HTTP headers so that all spans produced by the agent appear
    as children of the caller's span.

    Expected request body:
    {
        "message": "Customer's message here",
        "customer_id": "optional-customer-id"
    }
    """
    logger.info(f"Received event: {json.dumps(event)}")

    setup_tracer_provider()
    parent_ctx = extract_context_from_headers(event.get("headers") or {})
    token = otel_context.attach(parent_ctx)

    tracer = trace.get_tracer(__name__)

    try:
        with tracer.start_as_current_span(
            "handle_request",
            kind=trace.SpanKind.SERVER,
            attributes={"http.method": "POST", "http.route": "/support"},
        ) as span:
            if isinstance(event.get("body"), str):
                body = json.loads(event["body"])
            else:
                body = event.get("body", event)

            message = body.get("message")
            if not message:
                span.set_attribute("http.status_code", 400)
                return {
                    "statusCode": 400,
                    "headers": CORS_HEADERS,
                    "body": json.dumps({"error": "Message is required"}),
                }

            customer_id = body.get("customer_id")
            span.set_attribute("customer.id", customer_id or "anonymous")

            result = invoke_support(message, customer_id)

            logger.info(f"Response generated by: {result['handled_by']}")
            span.set_attribute("agent.handled_by", result["handled_by"])
            span.set_attribute("agent.query_type", result["query_type"])
            span.set_attribute("http.status_code", 200)

            return {
                "statusCode": 200,
                "headers": CORS_HEADERS,
                "body": json.dumps({
                    "response": result["response"],
                    "metadata": {
                        "handled_by": result["handled_by"],
                        "query_type": result["query_type"],
                        "needs_escalation": result["needs_escalation"],
                    },
                }),
            }

    except Exception as e:
        logger.error(f"Error processing request: {str(e)}", exc_info=True)
        return {
            "statusCode": 500,
            "headers": CORS_HEADERS,
            "body": json.dumps({"error": "Internal server error"}),
        }
    finally:
        otel_context.detach(token)
        flush_traces()
